server:
  port: 8759

spring:
  profiles: springcloud1
eureka:
  instance:
    hostname: springcloud1
  client:
    serviceUrl:
      defaultZone: http://springcloud2:8760/eureka/,http://springcloud3:8761/eureka/