server:
  port: 8761

spring:
  profiles: springcloud3
eureka:
  instance:
    hostname: springcloud3
  client:
    serviceUrl:
      defaultZone: http://springcloud1:8759/eureka/,http://springcloud2:8760/eureka/