eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 9000
  
spring:
  application:
    name: service-feign
    
feign:
  hystrix:
    enabled: true
#关闭安全监测
management:
  security:
    enabled: false